### ISSUE TITLE
don't extract icon on second application launch (electron)

### ISSUE THREAD

**Issue by RagunovichVlad** [sentialx/extract-file-icon#4]
I have an electron app that fetch current activity icon every 1 second. `extract-file-icon` works good untill second launch of application. on second launch it returns nothing, buut if I change icon size param it start working again
Env:
Windows 10
node 11.15
electron 7.1.7

**Comment by anudeepreddy** [comment]
This keep happening with me as well. I get an empty buffer sometime when I launch the application

**Comment by anudeepreddy** [comment]
@RagunovichVlad Did your issue get resolved?

**Comment by cronvel** [comment]
Same here, sometime I get zero-length buffer for no reason.
